project_name: mirage
model_name: mirage

train_dataset_url: {your_s3_path}/shard-{000000..009995}.tar
val_dataset_url: {your_s3_path}/shard-{009996..009999}.tar

# Training parameters
optimizer: Adam
lr: 0.0005
weight_decay: 0.05
scheduler_step: 25000
scheduler_decay: 0.9
max_epochs: 5
log_every_n_steps: 100
num_workers: 16
batch_size: 8

num_enc_layers: 3
num_dec_layers: 3
grid_size: 40.0
update_octree: false
max_lod: 9
min_lod: 5
num_heads: 3
dim_model: 32
dim_mae: 192
pos_emb_dim: 21
resid_dropout: 0.0
ff_dropout: 0.0
ff_activation: gelu
ff_hidden_layer_multiplier: 8
